import type { IDisplayOptions, INodeProperties } from 'n8n-workflow';
import { sessionField } from './common';

const showFor = (operation: string[]): IDisplayOptions => ({
	show: { resource: ['system'], operation },
});

export const systemOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['system'] } },
	options: [
		{
			name: 'Get Audit Log',
			value: 'getAuditLog',
			action: 'Get the audit log',
			description: 'List audit log entries, one item per entry',
		},
		{
			name: 'Get Health',
			value: 'getHealth',
			action: 'Get the gateway health',
			description: 'Basic health check with the gateway version',
		},
		{
			name: 'Get Liveness',
			value: 'getLiveness',
			action: 'Get the gateway liveness',
			description: 'Check that the gateway process answers',
		},
		{
			name: 'Get Message Stats',
			value: 'getMessageStats',
			action: 'Get message statistics',
			description: 'Message counts over time, by type, by session and by chat',
		},
		{
			name: 'Get Overview',
			value: 'getOverview',
			action: 'Get the statistics overview',
			description: 'Session and message totals across all sessions',
		},
		{
			name: 'Get Readiness',
			value: 'getReadiness',
			action: 'Get the gateway readiness',
			description:
				'Check that the gateway databases respond. A failing dependency is output with status "error" rather than failing the node.',
		},
		{
			name: 'Get Session Stats',
			value: 'getSessionStats',
			action: 'Get session statistics',
			description: 'Message counts, top chats and hourly activity of one session',
		},
		{
			name: 'Get Settings',
			value: 'getSettings',
			action: 'Get the gateway settings',
			description: 'Read the gateway settings (general, API and notifications)',
		},
		{
			name: 'Search Messages',
			value: 'searchMessages',
			action: 'Search messages',
			description:
				'Full-text search across stored messages, one item per hit. Needs a search provider on the gateway.',
		},
	],
	default: 'getHealth',
};

const returnAllFields = (operation: string): INodeProperties[] => [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: showFor([operation]),
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		displayOptions: { show: { resource: ['system'], operation: [operation], returnAll: [false] } },
		description: 'Max number of results to return',
	},
];

export const systemFields: INodeProperties[] = [
	{
		displayName: 'Period',
		name: 'statsPeriod',
		type: 'options',
		options: [
			{ name: 'Last 24 Hours', value: '24h' },
			{ name: 'Last 7 Days', value: '7d' },
			{ name: 'Last 30 Days', value: '30d' },
		],
		default: '24h',
		displayOptions: showFor(['getMessageStats']),
		description: 'Time window of the returned series',
	},
	{
		...sessionField,
		name: 'statsSession',
		description: 'The OpenWA session to get statistics for',
		displayOptions: showFor(['getSessionStats']),
	},
	{
		displayName: 'Query',
		name: 'searchQuery',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. invoice',
		displayOptions: showFor(['searchMessages']),
		description: 'The text to search for',
	},
	...returnAllFields('getAuditLog'),
	...returnAllFields('searchMessages'),
	{
		displayName: 'Filters',
		name: 'auditFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: showFor(['getAuditLog']),
		options: [
			{
				displayName: 'Action',
				name: 'action',
				type: 'options',
				options: [
					{ name: 'API Key Auth Failed', value: 'api_key_auth_failed' },
					{ name: 'API Key Created', value: 'api_key_created' },
					{ name: 'API Key Deleted', value: 'api_key_deleted' },
					{ name: 'API Key Revoked', value: 'api_key_revoked' },
					{ name: 'API Key Updated', value: 'api_key_updated' },
					{ name: 'API Key Used', value: 'api_key_used' },
					{ name: 'Infra Config Saved', value: 'infra_config_saved' },
					{ name: 'Infra Data Exported', value: 'infra_data_exported' },
					{ name: 'Infra Data Imported', value: 'infra_data_imported' },
					{ name: 'Infra Restart Requested', value: 'infra_restart_requested' },
					{ name: 'Infra Storage Exported', value: 'infra_storage_exported' },
					{ name: 'Infra Storage Imported', value: 'infra_storage_imported' },
					{ name: 'Integration Instance Created', value: 'integration_instance_created' },
					{ name: 'Integration Instance Deleted', value: 'integration_instance_deleted' },
					{ name: 'Integration Instance Redriven', value: 'integration_instance_redriven' },
					{
						name: 'Integration Instance Secret Regenerated',
						value: 'integration_instance_secret_regenerated',
					},
					{ name: 'Integration Instance Updated', value: 'integration_instance_updated' },
					{ name: 'Message Failed', value: 'message_failed' },
					{ name: 'Message Sent', value: 'message_sent' },
					{ name: 'Queue Board Mutated', value: 'queue_board_mutated' },
					{ name: 'Rate Limit Exceeded', value: 'rate_limit_exceeded' },
					{ name: 'Send Breaker Tripped', value: 'send_breaker_tripped' },
					{ name: 'Send Pacing Blocked', value: 'send_pacing_blocked' },
					{ name: 'Session Config Updated', value: 'session_config_updated' },
					{ name: 'Session Connected', value: 'session_connected' },
					{ name: 'Session Created', value: 'session_created' },
					{ name: 'Session Deleted', value: 'session_deleted' },
					{ name: 'Session Disconnected', value: 'session_disconnected' },
					{ name: 'Session Force Killed', value: 'session_force_killed' },
					{ name: 'Session Logged Out', value: 'session_logged_out' },
					{ name: 'Session QR Generated', value: 'session_qr_generated' },
					{ name: 'Session Rebind Rejected', value: 'session_rebind_rejected' },
					{ name: 'Session Restricted', value: 'session_restricted' },
					{ name: 'Session Restriction Lifted', value: 'session_restriction_lifted' },
					{ name: 'Session Started', value: 'session_started' },
					{ name: 'Session Stopped', value: 'session_stopped' },
					{ name: 'Webhook Created', value: 'webhook_created' },
					{ name: 'Webhook Deleted', value: 'webhook_deleted' },
					{ name: 'Webhook Failed', value: 'webhook_failed' },
					{ name: 'Webhook Triggered', value: 'webhook_triggered' },
				],
				default: 'message_sent',
			},
			{
				displayName: 'API Key ID',
				// Not `apiKeyId`: the linter forces params named apiKey* to be password fields.
				name: 'keyId',
				type: 'string',
				default: '',
				description: 'Only entries made with this API key',
			},
			{
				displayName: 'Session ID',
				name: 'sessionId',
				type: 'string',
				default: '',
				description: 'Only entries about this session (its ID, not its name)',
			},
			{
				displayName: 'Severity',
				name: 'severity',
				type: 'options',
				options: [
					{ name: 'Error', value: 'error' },
					{ name: 'Info', value: 'info' },
					{ name: 'Warning', value: 'warn' },
				],
				default: 'error',
			},
		],
	},
	{
		displayName: 'Filters',
		name: 'searchFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: showFor(['searchMessages']),
		options: [
			{
				displayName: 'Chat',
				name: 'chatId',
				type: 'string',
				default: '',
				placeholder: 'e.g. 972501234567 or 120363000000000000@g.us',
				description: 'Only messages in this chat: a phone number, or a full chat ID',
			},
			{
				displayName: 'Date From',
				name: 'dateFrom',
				type: 'dateTime',
				default: '',
				description:
					'Only messages at or after this time, in the workflow timezone unless the value has an offset',
			},
			{
				displayName: 'Date To',
				name: 'dateTo',
				type: 'dateTime',
				default: '',
				description:
					'Only messages at or before this time, in the workflow timezone unless the value has an offset',
			},
			{
				displayName: 'Direction',
				name: 'direction',
				type: 'options',
				options: [
					{ name: 'Incoming', value: 'incoming' },
					{ name: 'Outgoing', value: 'outgoing' },
				],
				default: 'incoming',
			},
			{
				displayName: 'Sender',
				name: 'from',
				type: 'string',
				default: '',
				placeholder: 'e.g. 972501234567',
				description: 'Only messages from this contact: a phone number, or a full contact ID',
			},
			{
				displayName: 'Session ID',
				name: 'sessionId',
				type: 'string',
				default: '',
				description: 'Only messages of this session (its ID, not its name)',
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'string',
				default: '',
				placeholder: 'e.g. text',
				description: 'Only messages of this type, e.g. text, image or document',
			},
		],
	},
];
